#!/usr/bin/php
<?php
$cwd = getcwd();
$dest = '/home/build_ctl/www/vendor/doctrine/dbal/lib';

$links = explode("\n", `find Doctrine/ -type f`);

foreach($links as $lv){
	if(strpos($lv, '/')===FALSE) continue;
	 $newdir = $dest.'/'.substr($lv, 0, strrpos($lv, '/') );
	`mkdir -p {$newdir}`;
	`ln -s {$cwd}/{$lv} {$dest}/{$lv}`;
}
